nama = input("Masukkan nama : ")
umur = input("Masukkan umur : ")
alamat = input("Masukkan alamat : ")
jurusan = input("Masukkan jurusan : ")

print("\n-----Biodata-----")
print("Nama : " + nama)
print("Umur : " + umur)
print("Alamat : " + alamat)
print("Jurusan : " + jurusan)
